// <auto-generated />
using ConectaStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConectaStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConectaStore.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#FF5733",
                            Nome = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#33FF57",
                            Nome = "Notebooks"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#3357FF",
                            Nome = "SmartWatches"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#FF33A1",
                            Nome = "Fones de Ouvido"
                        });
                });

            modelBuilder.Entity("ConectaStore.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Qtde")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "O iPhone 17 Pro é o mais recente lançamento da Apple, trazendo um design elegante e recursos avançados. Com uma tela Super Retina XDR de 6,1 polegadas, o dispositivo oferece uma experiência visual imersiva. Equipado com o chip A17 Bionic, o iPhone 17 Pro proporciona desempenho excepcional e eficiência energética. O sistema de câmera tripla inclui uma lente principal de 12 MP, uma lente ultra-angular de 12 MP e uma lente telefoto de 12 MP, permitindo fotos e vídeos de alta qualidade. Além disso, o iPhone 17 Pro suporta carregamento rápido e possui resistência à água e poeira IP68.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-17-pro-gold-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "iPhone 17 Pro",
                            Qtde = 0,
                            ValorCusto = 1000m,
                            ValorVenda = 10000.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descricao = "O MacBook Air é o notebook mais leve e portátil da Apple, ideal para uso diário e produtividade. Com o chip M2, oferece desempenho excepcional e eficiência energética. A tela Retina de 13,6 polegadas proporciona uma experiência visual imersiva. O MacBook Air é leve, silencioso e oferece até 18 horas de autonomia.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-m2-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "MacBook Air",
                            Qtde = 0,
                            ValorCusto = 2000m,
                            ValorVenda = 20000.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descricao = "O Apple Watch Series 9 é o smartwatch mais avançado da Apple, oferecendo uma combinação perfeita de estilo e funcionalidade. Com um design elegante e uma tela Retina sempre ativa, o Series 9 é ideal para monitorar sua saúde e fitness. Ele possui recursos como monitoramento de frequência cardíaca, rastreamento de atividades físicas, detecção de quedas e suporte a aplicativos de terceiros. O Apple Watch Series 9 é resistente à água e oferece uma bateria de longa duração para mantê-lo conectado durante todo o dia.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-watch-series-9-gps-select?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "Apple Watch Series 9",
                            Qtde = 0,
                            ValorCusto = 300m,
                            ValorVenda = 2500.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descricao = "Os AirPods Pro são os fones de ouvido sem fio premium da Apple, oferecendo uma experiência de áudio imersiva e cancelamento ativo de ruído. Com um design compacto e confortável, os AirPods Pro se encaixam perfeitamente nos ouvidos. Eles possuem um modo de transparência que permite ouvir o ambiente ao seu redor quando necessário. Os AirPods Pro são resistentes à água e suor, tornando-os ideais para atividades físicas. Com uma bateria de longa duração e suporte a carregamento sem fio, os AirPods Pro são a escolha perfeita para quem busca qualidade de áudio e conveniência.",
                            Destaque = true,
                            Foto = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22?wid=940&hei=1112&fmt=png-alpha&.v=1700792800",
                            Nome = "AirPods Pro",
                            Qtde = 0,
                            ValorCusto = 700m,
                            ValorVenda = 5600.00m
                        });
                });

            modelBuilder.Entity("ConectaStore.API.Models.Produto", b =>
                {
                    b.HasOne("ConectaStore.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
